### PR TITLE
feat: make `hash_function` as parameter

### LINKED ISSUE #3: Allow hash function to be parametrized
It would cool if we set the hash function upon initialization

### LINKED ISSUE #4: Mutable default argument
`leaves=[]` is a problematic default.

look at this for example: https://stackoverflow.com/questions/1132941/least-astonishment-and-the-mutable-default-argument

### PR DESCRIPTION
**Pull request by antazoey**
* Allows hash function to be parametrized
* Fixes a mutable default argument bug

fixes: #3 
fixes: #4

### CODE REVIEW

**Comment by jvsteiner** [comment]
I'll take a look, but may I ask why you would bother to write code for this implementation?  You can probably get a better one out of ChatGPT in 20 seconds these days...

**Comment by antazoey** [comment]
> I'll take a look, but may I ask why you would bother to write code for this implementation? You can probably get a better one out of ChatGPT in 20 seconds these days...

Feel free to ignore

**Comment by jvsteiner** [comment]
not at all, I will happily review.

**Comment by antazoey** [comment]
So you are right, I ended up using different code entirely!
I think this is just a product of how I work though - I start at the basics and try to just do something, it forces me to get familiar with the topics.

But also!!! Why does javascript get all the nice things? Like I love the [OpenZeppelin Javascript library for merkle trees](https://github.com/OpenZeppelin/merkle-tree), I was like "Hey, maybe Python has something too!". I found this library and just started playing around.

**Comment by jvsteiner** [comment]
well, I was just reviewing your comment about mutable default arguments, and really learned something new.    I will look out for that in the future, and I thank you for bringing it to my attention.

**Pull request merged**
